version: '3.7'
services:

  db:
    container_name: sakilaDBDocker
    image: budougumi0617/mysql-sakila
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sakilapwd
    volumes:
      - ./dbdata:/var/lib/mysql
    ports: 
       - "3306:3306"